server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: broker:9092
    partitions: 20
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: broker:9092
      enable-auto-commit: false
      topic: "transaction-1"
    listener:
      ack-mode: manual
      concurrency: 100


